name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Git LFS
        run: |
          git lfs install
          git lfs track "*.your-file-extension" # Remplacez par les extensions à suivre
          git add .gitattributes
          git commit -m "Configure Git LFS"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://Sahm269:$HF_TOKEN@huggingface.co/spaces/Sahm269/NutrigenieLLM main
