name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git identity
        run: |
          git config --global user.email "sourayatahmed18@gmail.com"
          git config --global user.name "Sahm269"
      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull
          git lfs track "*.json"
          git lfs track "server/security/data/guardrail_dataset_train_multi.json"
          git lfs track "envLLM/Lib/site-packages/numpy.libs/libscipy_openblas64_-43e11ff0749b8cbe0a615c9cf6737e0e.dll"
          git lfs track "envLLM/Lib/site-packages/pyarrow/arrow.dll"
          git add .gitattributes
          git add .
          git commit -m "Configure Git LFS"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://sahm269:$HF_TOKEN@huggingface.co/spaces/Sahm269/NutrigenieLLM main
